language: julia
os:
    - linux
    - osx
julia:
    - 0.3
    - 0.4
    - nightly
notifications:
    email: false

script: 
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'versioninfo(); Pkg.init(); Pkg.clone(pwd()); Pkg.test("FactCheck", coverage=true)'
